# Generated by Django 3.1.1 on 2021-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20211114_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_no',
            field=models.CharField(blank=True, default='7118279428', editable=False, max_length=10, unique=True),
        ),
    ]
